name: Run Shell Commands

on:[push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a String
        run: echo " we feel like boss  when writing commands but we must solve problems to feed our family 🥳🥳🥳"
